## FIRST LINE/ROW: Info & Status
[username]
format = "[$user]($style)@"
style_user = "bold #6272a4"
style_root = "bold #6272a4"
show_always = true

# Second param
[hostname]
format = "[$hostname]($style) in "
style = "bold #6272a4"
trim_at = "-"
ssh_only = false
disabled = false

# Third param
[directory]
style = '#bd93f9'
truncation_length = 0
truncate_to_repo = true
truncation_symbol = "repo: "

# Before all the version info (python, nodejs, php, etc.)
[git_status]
style = "#ffb86c"
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
deleted = "x"

# Last param in the first line/row
[cmd_duration]
min_time = 1
format = "took [$duration]($style)"
disabled = true


## SECOND LINE/ROW: Prompt
# Somethere at the beginning

# Prompt: param 1
[character]
success_symbol = '[❯](bold #bd93f9)'
error_symbol = '[❯](bold red)'

