## FIRST LINE/ROW: Info & Status
[username]
format = " [$user]($style)@"
style_user = "bold #6272a4"
style_root = "bold #6272a4"
show_always = true

# Second param
[hostname]
format = "[$hostname]($style) in "
style = "bold #6272a4"
trim_at = "-"
ssh_only = false
disabled = false

# Third param
[directory]
style = '#bd93f9'
truncation_length = 0
truncate_to_repo = true
truncation_symbol = "repo: "

# Before all the version info (python, nodejs, php, etc.)
[git_status]
style = "dimmed white"
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
deleted = "x"

# Last param in the first line/row
[cmd_duration]
min_time = 1
format = "took [$duration]($style)"
disabled = true


## SECOND LINE/ROW: Prompt
# Somethere at the beginning


# Prompt: param 2 
[character]
success_symbol = '[❯](bold fg:177)'
error_symbol = '[❯](bold red)'

# SYMBOLS
[status]
symbol = "🔴"
format = '[\[$symbol$status_common_meaning$status_signal_name$status_maybe_int\]]($style)'
map_symbol = true
disabled = false



