[username]
format = "[$user]($style)@"
style_user = "bold #5E81AC"
style_root = "bold #5E81AC"
show_always = true 
disabled = true

[hostname]
format = "[$hostname]($style) in "
style = "bold #5E81AC"
trim_at = "-"
ssh_only = false
disabled = true 

[directory]
style = 'bold #5E81AC'
truncation_length = 0
truncate_to_repo = true
#truncation_symbol = "repo: "

[git_status]
style = "#EBCB8B"
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
deleted = "x"

[git_state]
style = '#EBCB8B'

[git_branch]
style = '#EBCB8B'

[cmd_duration]
min_time = 1
format = "took [$duration]($style)"
disabled = true


[character]
success_symbol = '[❯](bold #88C0D0)'
error_symbol = '[❯](bold #BF616A)'
vicmd_symbol = '[❮](bold #A3BE8C)'
